//
// Created by 哒哒 on 2017/10/31.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyx_ajnp_MainActivity */

#ifndef _Included_com_dyx_ajnp_MainActivity
#define _Included_com_dyx_ajnp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyx_ajnp_MainActivity
 * Method:    setText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dyx_ajnp_MainActivity_setText
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_dyx_ajnp_MainActivity
 * Method:    getText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyx_ajnp_MainActivity_getText
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

