/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyx_rvap_MainActivity */

#ifndef _Included_com_dyx_rvap_MainActivity
#define _Included_com_dyx_rvap_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyx_rvap_MainActivity
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyx_rvap_MainActivity_getMsg
  (JNIEnv *, jclass);

/*
 * Class:     com_dyx_rvap_MainActivity
 * Method:    setMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_dyx_rvap_MainActivity_setMsg
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
