/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dyx_ip_jni_JniTest */

#ifndef _Included_com_dyx_ip_jni_JniTest
#define _Included_com_dyx_ip_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dyx_ip_jni_JniTest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyx_ip_jni_JniTest_get
  (JNIEnv *, jobject);

/*
 * Class:     com_dyx_ip_jni_JniTest
 * Method:    setContent
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dyx_ip_jni_JniTest_setContent
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
